# Generated by Django 4.2.7 on 2023-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_found_img_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="found_img",
            name="box_x1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="found_img",
            name="box_x2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="found_img",
            name="box_y1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="found_img",
            name="box_y2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="found_img",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="found_img",
            name="im_class",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="found_img",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
